# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: native
font_size: L

# SEO
site_type: 'ResearchOrganization'
local_business_type: ''
org_name: 'Theoretical Computer Science (TCS) in Amsterdam'
description: 'Overview website of academic research in theoretical computer science (TCS) carried out in Amsterdam, The Netherlands.'
twitter: ''

# Contact (edit or remove options as required)

email: c.schaffner@uva.nl
#phone: 888 888 88 88
address:
  street: Science Park
  city: Amsterdam
  region: NH
  postcode: '1090 GB'
  country: Netherlands
  country_code: NL
coordinates:
  latitude: '52.3548'
  longitude: '4.9545'
#directions: Enter LAB42
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
#contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: '02 Jan 2006'
time_format: '15:04'
address_format: nl


# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  wowchemy:
    min_length: 1  # Only the matches whose length exceeds this value will be returned.
    threshold: 1  # Where 0 requires a perfect match and 1 matches anything.
  algolia:
    app_id: '7QFR99CH9V'
    api_key: '62b50ee358709464f9458f04b7f3e6f8'
    index_name: 'website_theory_amsterda'
    show_logo: true
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: 'G-3LPXHP2BB3'
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
